{% set name = "QuantLib-python" %}
{% set version = "1.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lballabio/QuantLib-SWIG/releases/download/v{{ version }}/QuantLib-SWIG-{{ version }}.tar.gz
  sha256: 8b0d5536701ff1b5752d635c7610e639f4a52de99cd9d91aa01cf9073d80953e
  patches:
    - no-isolation.diff

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - swig
  host:
    - python
    - pip
    - libboost-devel
    - setuptools
    - python-build
    - quantlib =={{ version }}
    - pytest
  run:
    - python
    - quantlib  # [not win]

test:
  requires:
    - pytest
  source_files:
    - Python/test/*
  commands:
    - pytest Python/test/

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The python wrapper of QuantLib.
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
