{% set name = "QuantLib-python" %}
{% set version = "1.31.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib-SWIG/releases/download/v{{ version }}/QuantLib-SWIG-{{ version }}.tar.gz
  sha256: 6cc5874e674697c0cf3043e744b9269c8bc1e8b521888a1c9d7a711041c7d959

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - swig
  host:
    - python
    - pip
    - boost-cpp
    - quantlib =={{ version }}

  run:
    - python
    - quantlib  # [not win]
    - boost-cpp  # [win]

test:
  source_files:
    - Python/test/*
  commands:
    - python Python/test/QuantLibTestSuite.py

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The python wrapper of QuantLib.
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
