{% set name = "QuantLib-python" %}
{% set version = "1.29" %}
{% set sha256 = "1671fcd0c49363e38c3a69184b6938fa0df8718489ff6b07503dc056b0e2d10a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib-SWIG/archive/refs/tags/QuantLib-SWIG-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - swig
  host:
    - python
    - pip
    - boost-cpp
    - quantlib =={{ version }}

  run:
    - python
    - quantlib

test:
  imports:
    - QuantLib

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The python wrapper of QuantLib.
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
