{% set name = "QuantLib-python" %}
{% set version = "1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib-SWIG/releases/download/v{{ version }}/QuantLib-SWIG-{{ version }}.tar.gz
  sha256: d5248ed4f50be9f1ac0bab7dd876010725a8230e94e6a7b1305623d9ee574e47

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - swig
  host:
    - python
    - pip
    - libboost-devel
    - quantlib =={{ version }}

  run:
    - python
    - quantlib  # [not win]

test:
  source_files:
    - Python/test/*
  commands:
    - python Python/test/QuantLibTestSuite.py

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The python wrapper of QuantLib.
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
